# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://suyog7130.github.io/"
title: Suyog Garg
copyright: "© [Suyog Garg](https://github.com/Suyog7130)"
theme: [hugo-PaperMod]
pagination:
  pagerSize: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: [""]

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 2
        - name: Search
          url: search/
          weight: 1
        - name: Tags
          url: tags/
          weight: 3
        - name: captures
          url: https://captures.suyoggarg.com/
          weight: 4

  hi:
    languageName: "हिंदी"
    weight: 2
    title: Suyog Garg
    taxonomies:
      category: HIcategories
      tag: HItags
      series: HIseries
    menu:
      main:
        # - name: Archive
        #   url: archives-hi
        #   weight: 5
        - name: HITags
          url: hitags
          weight: 10
        # - name: 
        #   url: hicategories
        #   weight: 10
        # - name: HISeries
        #   url: hiseries
        #   weight: 10
        # - name: NullLink
        #   url: "#"

    # custom params for each language should be under [langcode].parms - hugo v0.120.0
    params:
      languageAltTitle: Hindi
      profileMode:
        enabled: true
        title: सुयोग गर्ग
        imageUrl: "images/suyog_cropped.png"
        imageTitle: my-image
        # imageWidth: 120
        # imageHeight: 120
        subtitle: ""
        buttons:
          - name: पृष्ठ
            url: multi-lingual/hindi/pages
          - name: ब्लॉग
            url: multi-lingual/hindi/posts

  ja:
    languageName: "日本語"
    languagedirection: rtl
    weight: 3
    title: Suyog Garg
    taxonomies:
      category: JAcategories
      tag: JAtags
      series: JAseries
    menu:
      main:
        - name: JATags
          url: jatags
          weight: 10
    # custom params for each language should be under [langcode].parms - hugo v0.120.0
    params:
      profileMode:
        enabled: false
      homeInfoParams:
        Title: "\U0001F44B スイオグ ガーグ"
        Content: 〜ウェブサイトへようこそ

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "My Personal Webpage !"
  author: Suyog Garg
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  # comments: false
  images: [""]

  # ShareButtons: ["linkedin", "twitter"]
  math: true
  comments: true
  UseHugoToc: true
  # DateFormat: ""
  # mainSections:
  #   - posts
  #   - projects
  #   - teaching

  profileMode:
    enabled: true
    title: Suyog Garg
    imageUrl: "images/suyog_cropped.png"
    imageTitle: my-image
    # imageWidth: 120
    # imageHeight: 120
    subtitle: "Physics PhD @ UTokyo"
    buttons:
      - name: About
        url: pages/about
        weight: 1
      - name: News
        url: pages/news
        weight: 2
      - name: Publications
        url: pages/publications
        weight: 3
      - name: Talks
        url: pages/talks
        weight: 4
      - name: Research
        url: research
        weight: 5
      - name: Posts
        url: posts
        weight: 6
      - name: CV
        url: pages/cv
        weight: 7
      - name: Personal
        url: pages/personal
        weight: 10

  homeInfoParams:
    Title: ""
    Content: >

      # ![](/images/suyog-ueno-dslr-pic-by-vivi-cropped.jpeg)

      # >
      # ![](https://readme-typing-svg.herokuapp.com?font=Tangerine&color=36454F&size=50&duration=5500&width=600&height=75&center=true&repeat=true&lines=Heya!+This+is+Suyog!;I'm+an+aspiring+Astrophysicist!;I+love+Books!;I'm+an+avid+Traveller!)
      
      # >
     
      # <h3>Heya 👋 this is Suyog. Here's some fun facts about me:</h3>

      # -  👀  I adore Books, Places and Astrophysics.

      # -  🌱  I research on using Machine Learning for Gravitational-Wave detection.

      # -  💻  I have experience in Data Analysis, Numerical Solvers and Deep Neural Nets.

      # -  💞️  Would be awesome to collaborate on a computational project.

      # -  📫  Catch up about my work on this website.


  socialIcons:
    - name: location
      title: My currrent location
      url: "Tokyo, Japan"
    - name: email
      title: Send me an Email
      url: "mailto:suyog7130@gmail.com"
    - name: github
      title: View Source on Github
      url: "https://github.com/Suyog7130"
    - name: ads
      title: My NASA-ADS Library
      url: "https://ui.adsabs.harvard.edu/public-libraries/rXwbbw00ScyGUUwLbBi0Nw"
    - name: googlescholar-acad
      title: My Google Scholar Page
      url: "https://scholar.google.com/citations?user=3co-LmUAAAAJ&hl=en"
    - name: arxiv
      title: My Arxiv Page
      url: "https://arxiv.org/search/advanced?advanced=&terms-0-operator=AND&terms-0-term=Garg%2C+Suyog&terms-0-field=author&classification-physics_archives=all&classification-include_cross_list=include&date-filter_by=all_dates&date-year=&date-from_date=&date-to_date=&date-date_type=submitted_date&abstracts=show&size=50&order=-announced_date_first"
    - name: orcid
      title: My ORCID Page
      url: "http://orcid.org/0000-0002-2309-9731"
    - name: researchgate
      title: My ResearchGate Profile
      url: "https://www.researchgate.net/profile/Suyog-Garg-2"
    - name: cv-acad
      title: Read my Resume / CV
      url: "pages/cv"
    - name: linkedin
      title: My LinkedIn Page
      url: "https://www.linkedin.com/in/suyog-garg/"
    - name: blogger
      title: My Blog
      url: "https://blog.suyoggarg.com"
    - name: twitter-fa
      title: My Twitter Page
      url: "https://twitter.com/SuyogGarg7130"
    - name: KoFi
      title: Buy me a Ko-Fi :)
      url: "https://ko-fi.com/suyoggarg"

  # editPost:
  #   URL: "https://github.com/Suyog7130/"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  label:
    iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
    # text: "Suyog Garg"
    icon: "images/sg-favicon-crop-circle.png"
    iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
    favicon: "images/sg-favicon-crop-invert.png"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
